steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/gcpdevops:latest", "."]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/gcpdevops:latest"]

  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
      - run
      - --filename=gke.yaml
      - --image=gcr.io/$PROJECT_ID/gcpdevops:latest
      - --location=asia-south1-a
      - --cluster=gke-gcp-devops
      - --namespace=gcp-devops-prod

options:
  logging: CLOUD_LOGGING_ONLY
