steps:
  - name: "docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/gcpdevops-dev", "."]

  - name: "docker"
    args: ["push", "gcr.io/$PROJECT_ID/gcpdevops-dev"]

  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
      - run
      - --filename=gke.yaml
      - --image=gcr.io/$PROJECT_ID/gcpdevops-dev
      - --location=asia-south1-a
      - --cluster=gcp-devops
      - --namespace=gcp-devops-prod

options:
  logging: CLOUD_LOGGING_ONLY
