steps:
  - name: "docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/gcpdevops", "."]

  - name: "docker"
    args: ["push", "gcr.io/$PROJECT_ID/gcpdevops"]

  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
      - run
      - --filename=gke.yaml
      - --image=gcr.io/$PROJECT_ID/gcpdevops
      - --location=asia-south1-a
      - --cluster=gcp-devops-project
      - --namespace=gcp-devops-prod

options:
  logging: CLOUD_LOGGING_ONLY
